version: "3.9"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"       # Porta da API do MinIO
      - "9001:9001"       # Porta do console do MinIO
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
